

services:
  db:
    image: mysql:8.0
    container_name: mysql_db2
    environment:
      MYSQL_ROOT_PASSWORD: "abcd"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "abcd"
      MYSQL_DATABASE: "tracker"  # 必要ならデフォルトDBも作成
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pma2
    depends_on:
      - db
    environment:
      PMA_HOST: db
      # PMA_USER, PMA_PASSWORD を削除
      MYSQL_ROOT_PASSWORD: "abcd"
    ports:
      - "8080:80"

  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_app2
    depends_on:
      - db
    ports:
      - "8000:8000"
    # DB に接続する場合は環境変数を定義
    environment:
      DB_HOST: db
      DB_USER: "user"
      DB_PASSWORD: "abcd"
      DB_NAME: "tracker"



volumes:
  db-data:
